### ISSUE TITLE
Additional context disabling of input parameter fields

### ISSUE THREAD

**Issue by bmpotter** [genetic-algorithms/mendel-go-spc#1]
Here are additional enabling/disabling rules. It gets a little confusing to precisely define these verbally. For additional info, see the comments in the defaults file, or ask me.

- **fitness_effect_model==fixed**
    - uniform_fitness_effect_del and uniform_fitness_effect_fav should only be enabled for this case, otherwise disabled
- **frac_fav_mutn==0.0**
    - disable max_fav_fitness_gain, uniform_fitness_effect_fav
- **selection_model==partialtrun**
    - partial_truncation_value (new default param) should only be enabled for this case
- **num_contrasting_alleles==0**
    - the 4 params under this should be disabled
- **initial_allele_fitness_model==variablefreq**
    - disable initial_alleles_pop_frac
- **initial_allele_fitness_model==allunique**
    - disable initial_alleles_frequencies
- **pop_growth_model==none**
    - disable all 4 params under this **and** all 3 bottleneck params
- **pop_growth_model==founders**
    - enable all pop growth and bottleneck params except max_pop_size
- **pop_growth_model==capacity**
    - enable pop_growth_rate and carrying_capacity
- **pop_growth_model==exponential**
    - enable pop_growth_rate and max_pop_size
- **bottleneck_generation==0**
    - disable the 2 bottleneck params under this
- **files_to_output_allele_bins==false && files_to_output_all=false**
    - disable tracking_threshold, plot_allele_gens, and omit_first_allele_bin

**Comment by jpotterm** [comment]
Fixed in e699dacccbe9280c27819313006ca01d3c6140fd.
